"""
Django settings for booking project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
from datetime import timedelta
from pathlib import Path
import sys
from decouple import config, Csv
import environ
import os
import os
import os
import dj_database_url
from environ import Env
env = Env()


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

Env.read_env(BASE_DIR / ".env")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["malvabeauty.duckdns.org", "127.0.0.1"]


# Application definition

INSTALLED_APPS = [
    'phonenumbers',
    'anymail',
    'accounts',
    'core',
    'dal',
    'dal_select2',
    'storages',
    'jazzmin',
    "django.contrib.humanize",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'accounts.middleware.ForceAdminReAuthMiddleware'
]

ROOT_URLCONF = 'booking.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'booking.wsgi.application'

# FORM_RENDERER = 'django.forms.renderers.TemplatesSetting'
# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'Malva', # Change to your local DB name
        'USER': 'postgres', # Change to your local user name
        'PASSWORD': 'admin', # Change to your local user password
        'HOST': 'localhost',
        'PORT': '5433',
    }
}

# DATABASES = {
#     "default": env.db(
#         "DATABASE_URL",
#         default="postgres://postgres@localhost:5432/postgres",
#     )
# }


# DATABASES = {
#     "default": dj_database_url.parse(
#         os.environ["DATABASE_URL"],
#         conn_max_age=600,
#         ssl_require=False,
#     )
# }

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Edmonton'

USE_I18N = True

USE_TZ = True

# Сессия истекает через 1 час (3600 секунд)
SESSION_COOKIE_AGE = 3600

# Сессия закрывается при закрытии браузера (по желанию)
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# Опционально — продлевать сессию при активности пользователя
SESSION_SAVE_EVERY_REQUEST = True
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [ BASE_DIR / "static" ]

MEDIA_URL = env.str("MEDIA_URL", default="/media/")
MEDIA_ROOT = env.str("MEDIA_ROOT", default=str(BASE_DIR / "media"))
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# --- Payments / Stripe ---
STRIPE_PUBLIC_KEY = env(
    "STRIPE_PUBLISHABLE_KEY",
    default=os.environ.get("STRIPE_PUBLIC_KEY", ""),
)
STRIPE_SECRET_KEY = env("STRIPE_SECRET_KEY", default="")
STRIPE_WEBHOOK_SECRET = env("STRIPE_WEBHOOK_SECRET", default="")
STRIPE_CURRENCY = env("STRIPE_CURRENCY", default="cad")
STRIPE_API_VERSION = env("STRIPE_API_VERSION", default="2025-09-30.clover")
STRIPE_PAYMENT_METHOD_TYPES = env.list(
    "STRIPE_PAYMENT_METHOD_TYPES",
    default=["card"],
)
STRIPE_ALLOW_PROMISE_PAYMENT = env.bool(
    "STRIPE_ALLOW_PROMISE_PAYMENT",
    default=False,
)

# # Use S3 as default storage for uploaded media
# DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'

# # AWS credentials

# AWS_S3_SIGNATURE_NAME  = 's3v4'
# # Your S3 bucket name
# AWS_STORAGE_BUCKET_NAME = 'malvatest1'
# AWS_S3_REGION_NAME = 'ca-central-1'
# # Optional: Make files public
# AWS_QUERYSTRING_AUTH = False

# # Optional: Customize file URLs
# AWS_S3_FILE_OVERWRITE = False
# AWS_DEFAULT_ACL = None
# # Optional: Specify custom domain (if you use CloudFront or static hosting)
# # AWS_S3_CUSTOM_DOMAIN = f'{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com'

# AWS_ACCESS_KEY_ID=env("AWS_ACCESS_KEY_ID")
# AWS_SECRET_ACCESS_KEY=env("AWS_SECRET_ACCESS_KEY")

# settings.py
from environ import Env
env = Env()

USE_S3 = env.bool("USE_S3", default=False)

if USE_S3:
    INSTALLED_APPS += ["storages"]
    AWS_ACCESS_KEY_ID = env("AWS_ACCESS_KEY_ID")
    AWS_SECRET_ACCESS_KEY = env("AWS_SECRET_ACCESS_KEY")
    AWS_STORAGE_BUCKET_NAME = env("AWS_STORAGE_BUCKET_NAME")
    AWS_S3_REGION_NAME = env("AWS_S3_REGION_NAME", default="us-east-1")
    AWS_S3_SIGNATURE_VERSION = "s3v4"
    DEFAULT_FILE_STORAGE = "storages.backends.s3boto3.S3Boto3Storage"
else:
    # локально — файловая система
    # MEDIA_URL = "/media/"
    # MEDIA_ROOT = BASE_DIR / "media"
    STATIC_ROOT = "/app/storage/static"
    MEDIA_ROOT  = "/app/storage/media"
# # Media URL for S3
# MEDIA_URL = f'https://{AWS_STORAGE_BUCKET_NAME}.s3.ca-central-1.amazonaws.com/'
# REVIEW_FORM_URL = "https://your-domain.tld/review/{appointment_id}/"

# EMAIL_BACKEND = "anymail.backends.sendgrid.EmailBackend"
# ANYMAIL = {
#     "SENDGRID_API_KEY": env("SENDGRID_API_KEY"),
# }
# DEFAULT_FROM_EMAIL=env("DEFAULT_FROM_EMAIL")
# SERVER_EMAIL=env("SERVER_EMAIL")

  # для административных уведомлений
# хороший дефолт, чтобы Django формировал абсолютные ссылки в письмах:
from environ import Env
env = Env()

# ===== Email =====
USE_SENDGRID = env.bool("USE_SENDGRID", default=False)


DEFAULT_FROM_EMAIL = env.str("DEFAULT_FROM_EMAIL", default="noreply@example.com")
SENDGRID_SANDBOX_MODE_IN_DEBUG = env.bool("SENDGRID_SANDBOX_MODE_IN_DEBUG", default=False)
SENDGRID_ECHO_TO_STDOUT = env.bool("SENDGRID_ECHO_TO_STDOUT", default=False)


# --- Celery ---
CELERY_BROKER_URL = env.str("CELERY_BROKER_URL")
CELERY_RESULT_BACKEND = env.str("CELERY_RESULT_BACKEND")
CELERY_TIMEZONE = "America/Edmonton"
CELERY_ENABLE_UTC = True

# Периодический запуск: каждые 5 минут — одна задача сама решит, кому слать 48h и 3h
CELERY_BEAT_SCHEDULE = {
    "run-all-schedulers-every-5-min": {
        "task": "core.tasks.run_all_schedulers",
        "schedule": timedelta(minutes=5),
    },
}

# TWILIO_ACCOUNT_SID = env("TWILIO_ACCOUNT_SID")
# TWILIO_AUTH_TOKEN = env("TWILIO_AUTH_TOKEN")
# TWILIO_FROM_NUMBER = env("TWILIO_FROM_NUMBER")
from environ import Env
env = Env()

USE_TWILIO = env.bool("USE_TWILIO", default=False)

if USE_TWILIO:
    TWILIO_ACCOUNT_SID = env("TWILIO_ACCOUNT_SID")
    TWILIO_AUTH_TOKEN = env("TWILIO_AUTH_TOKEN")
    TWILIO_FROM_NUMBER = env("TWILIO_FROM_NUMBER")
else:
    # Локально заглушка, чтобы не падало
    TWILIO_ACCOUNT_SID = ""
    TWILIO_AUTH_TOKEN = ""
    TWILIO_FROM_NUMBER = ""

JAZZMIN_SETTINGS = {
    "site_title": "Malva Admin",
    "site_header": "Malva Health & Beauty",
    "welcome_sign": "Welcome to Malva",
    "copyright": "Malva © 2025",
    "search_model": ["auth.User"],
    "show_sidebar": False,
    "navigation_expanded": True,
    "show_ui_builder": False,
    "hide_models": ["Groups"],
    # Цвета темы (можно поменять)
    "topmenu_links": [
        {"name": "Webpage", "url": "/", "permissions": ["auth.view_user"]},
    ],
    "icons": {
        # Django
        "auth.User": "fas fa-user",
        "auth.Group": "fas fa-users-cog",

        # Core app
        "core.Appointment": "fas fa-calendar-check",
        "core.AppointmentStatus": "fas fa-info-circle",
        "core.AppointmentStatusHistory": "fas fa-history",
        "core.AppointmentPrepayment": "fas fa-coins",

        "core.ClientFile": "fas fa-file-alt",
        "core.Notification": "fas fa-bell",
        "core.Payment": "fas fa-money-check-alt",
        "core.PaymentMethod": "fas fa-credit-card",
        "core.PaymentStatus": "fas fa-receipt",

        "core.PrepaymentOption": "fas fa-percentage",

        "core.Role": "fas fa-user-tag",
        "core.UserRole": "fas fa-user-friends",

        "core.Service": "fas fa-spa",
        "core.ServiceMaster": "fas fa-user-cog",
    },
    "menu": [
    {
        "label": "📅 Appointments",
        "models": [
            "core.appointment",
            "core.appointmentstatus",
            "core.appointmentprepayment",
            "core.appointmentstatushistory",
        ],
    },
{
    "label": "🧑‍💼 Users",
    "models": [
        "core.user",
        "core.userprofile",
        "core.role",
        "core.userrole",
        "core.clientfile",
    ],
},
{
    "label": "💳 Payments",
    "models": [
        "core.payment",
        "core.paymentstatus",
        "core.paymentmethod",
    ],
},
{
    "label": "🛎️ Services",
    "models": [
        "core.service",
        "core.servicemaster",
    ],
},
{
    "label": "🔔 Notifications",
    "models": [
        "core.notification",
    ]
},
{
    "label": "👨‍🏫 Masters",
    "models": [
        "core.masterprofile",
        "core.masteravailability",
    ]
}
],
}
EMAIL_BACKEND = "anymail.backends.sendgrid.EmailBackend"
ANYMAIL = {
    "SENDGRID_API_KEY": env("SENDGRID_API_KEY"),
}
DEFAULT_FROM_EMAIL=env("DEFAULT_FROM_EMAIL")
SERVER_EMAIL=env("SERVER_EMAIL")

# для административных уведомлений
# хороший дефолт, чтобы Django формировал абсолютные ссылки в письмах:


JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": False,
    "accent": "accent-primary",
    "navbar": "navbar-white navbar-light",
    "no_navbar_border": False,
    "navbar_fixed": False,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "default",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-outline-primary",
        "secondary": "btn-outline-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    },
    "custom_css": "admin/css/admin_custom.css"
}

# booking/settings.py
LOGIN_URL = 'login'               # где лежит форма
# LOGIN_REDIRECT_URL = '/'          # fallback
# LOGOUT_REDIRECT_URL = 'login'     # опционально
AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",      # админы / мастера
    "core.auth_backends.EmailPhoneBackend",           # клиенты: username / e-mail / телефон
]
LOGIN_REDIRECT_URL = "/accounts/" 
LOGOUT_REDIRECT_URL = "/accounts/"
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# за прокси HTTPS
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
