# Generated by Django 5.2.4 on 2025-08-27 18:28

import django.contrib.auth.models
import django.core.validators
import django.db.models.deletion
import storages.backends.s3
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('final_price', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True)),
                ('discount_source', models.CharField(blank=True, default='', editable=False, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('personal_discount_percent', models.PositiveSmallIntegerField(default=0, editable=False, help_text='Personal discount snapshot at booking time', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CancellationReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClientSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='MasterProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.CharField(blank=True, max_length=100)),
                ('bio', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='MasterRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PrepaymentOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('discount_percent', models.PositiveIntegerField(help_text='discount in percents(0-100)')),
                ('active', models.BooleanField(default=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ReminderSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Visible name, e.g. '48h' or '3 hours before'", max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('offset_amount', models.PositiveIntegerField(help_text='How many hours/days before start')),
                ('offset_unit', models.CharField(choices=[('hours', 'Hours'), ('days', 'Days')], default='hours', max_length=8)),
                ('email_subject', models.CharField(default='Appointment reminder', max_length=200)),
                ('email_template', models.CharField(default='email/appointment_reminder.html', help_text='Django template path', max_length=200)),
                ('slug', models.SlugField(help_text="Used for deduplication, e.g. 'rem-48h'", max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-is_active', 'offset_unit', 'offset_amount', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration_min', models.IntegerField()),
                ('extra_time_min', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUserDisplay',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('unit_price_overridden', models.BooleanField(default=False, help_text='Manually set in admin')),
                ('final_price', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True)),
                ('discount_source', models.CharField(blank=True, default='', editable=False, max_length=20)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.appointment')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_items', to='core.masterprofile')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.service')),
            ],
        ),
        migrations.CreateModel(
            name='ClientReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1 ★'), (2, '2 ★'), (3, '3 ★'), (4, '4 ★'), (5, '5 ★')], help_text='Rating 1 to 5')),
                ('comment', models.TextField(blank=True, help_text='Not obligatory text comment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.OneToOneField(help_text='One review per one appointment', on_delete=django.db.models.deletion.CASCADE, related_name='review', to='core.appointment')),
            ],
            options={
                'verbose_name': 'Client Review',
                'verbose_name_plural': 'Client Reviews',
            },
        ),
        migrations.CreateModel(
            name='MasterAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('reason', models.CharField(choices=[('vacation', 'Vacation'), ('lunch', 'Lunch'), ('break', 'Break')], default='vacation', help_text='Reason for time off', max_length=20)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.masterprofile')),
            ],
            options={
                'verbose_name': 'Time Off / Vacation',
                'verbose_name_plural': 'Time Offs / Vacations',
            },
        ),
        migrations.AddField(
            model_name='masterprofile',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.masterroom'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.appointment')),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.paymentmethod')),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='payment_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.paymentstatus'),
        ),
        migrations.CreateModel(
            name='AppointmentPrepayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.appointment')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.prepaymentoption')),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentItemPromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('force_apply', models.BooleanField(default=False, help_text='Allow promo even if service discount is active')),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='promocode_link', to='core.appointmentitem')),
                ('promocode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.promocode')),
            ],
        ),
        migrations.AddField(
            model_name='promocode',
            name='applicable_services',
            field=models.ManyToManyField(blank=True, help_text='leave empty to apply to all services', to='core.service'),
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.servicecategory'),
        ),
        migrations.CreateModel(
            name='ServiceDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_percent', models.PositiveIntegerField(help_text='Percent of discount')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='core.service')),
            ],
            options={
                'verbose_name': 'Service Discount',
                'verbose_name_plural': 'Service Discounts',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ServiceMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.masterprofile')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.service')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=32, unique=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('email_marketing_consent', models.BooleanField(default=False)),
                ('email_marketing_consented_at', models.DateTimeField(blank=True, null=True)),
                ('how_heard', models.CharField(blank=True, choices=[('google', 'Google search'), ('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('friend', 'Friends/Family'), ('other', 'Other')], max_length=32)),
                ('notes', models.TextField(blank=True, null=True)),
                ('personal_discount_percent', models.PositiveSmallIntegerField(default=0, help_text="personal client's discount, % (0–100)", validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('health_conditions', models.JSONField(blank=True, default=dict)),
                ('postal_code', models.CharField(blank=True, help_text='Alberta postal code, 6 chars (e.g. T2X1A1)', max_length=6)),
                ('source', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], default='online', editable=False, max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS')], max_length=10)),
                ('kind', models.CharField(choices=[('reminder_days', 'Reminder Days'), ('reminder_hours', 'Reminder Hours'), ('created', 'Appointment created'), ('updated', 'Appointment updated'), ('cancelled', 'Appointment cancelled'), ('status', 'Appointment status changed'), ('other', 'Other')], default='other', max_length=32)),
                ('message', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.CharField(blank=True, default='sendgrid', max_length=32)),
                ('provider_message_id', models.CharField(blank=True, default='', max_length=128)),
                ('status', models.CharField(default='sent', max_length=20)),
                ('error', models.TextField(blank=True, default='')),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.appointment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='masterprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='master_profile', to='core.userprofile'),
        ),
        migrations.CreateModel(
            name='ClientFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(storage=storages.backends.s3.S3Storage(), upload_to='client_files/')),
                ('file_type', models.CharField(editable=False, max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.CharField(choices=[('user', 'User'), ('admin', 'Admin')], default='user', help_text='Who uploaded the file: admin or user', max_length=10)),
                ('description', models.CharField(blank=True, help_text="Optional description (e.g., 'Form before procedure')", max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.appointment')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.appointmentstatus')),
                ('cancellation_reason', models.ForeignKey(blank=True, help_text="Reason for cancelling if status is 'Cancelled'", null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cancellationreason')),
                ('set_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments_as_client', to='core.userprofile'),
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='MasterWorkDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workdays', to='core.masterprofile')),
            ],
            options={
                'ordering': ['weekday'],
                'unique_together': {('master', 'weekday')},
            },
        ),
        migrations.AddIndex(
            model_name='appointmentitem',
            index=models.Index(fields=['master', 'start_time'], name='core_appoin_master__42bc28_idx'),
        ),
        migrations.AddIndex(
            model_name='servicemaster',
            index=models.Index(fields=['master', 'service'], name='core_servic_master__9e8121_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='servicemaster',
            unique_together={('service', 'master')},
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(fields=('appointment', 'kind', 'channel'), name='uniq_notification_per_kind_channel'),
        ),
        migrations.AlterUniqueTogether(
            name='userrole',
            unique_together={('user', 'role')},
        ),
    ]
