# Generated by Django 5.2.4 on 2025-08-20 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='servicemaster',
            unique_together={('service', 'master')},
        ),
        migrations.AddIndex(
            model_name='servicemaster',
            index=models.Index(fields=['master', 'service'], name='core_servic_master__9e8121_idx'),
        ),
    ]
