# Generated by Django 5.2.4 on 2025-09-01 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_appointment_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='payment_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.paymentstatus'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.appointmentitem'),
        ),
    ]
