# Generated by Django 5.2.4 on 2025-08-20 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_servicemaster_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancellationReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='appointmentstatushistory',
            name='cancellation_reason',
            field=models.ForeignKey(blank=True, help_text="Reason for cancelling if status is 'Cancelled'", null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cancellationreason'),
        ),
    ]
