# Generated by Django 5.2.4 on 2025-09-01 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_appointment_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.appointment'),
        ),
    ]
