# Generated by Django 5.2.4 on 2025-08-20 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cancellationreason_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='prepayment_option',
        ),
    ]
