# Generated by Django 5.2.4 on 2025-08-20 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_service_prepayment_option'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterWorkDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workdays', to='core.masterprofile')),
            ],
            options={
                'ordering': ['weekday'],
                'unique_together': {('master', 'weekday')},
            },
        ),
    ]
