# Generated by Django 5.2.4 on 2025-09-02 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_notification_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentitem',
            name='discount_source',
            field=models.CharField(blank=True, default='', editable=False, max_length=40),
        ),
    ]
