# Generated by Django 5.2.4 on 2025-08-20 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_masterworkday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masterprofile',
            name='work_end',
        ),
        migrations.RemoveField(
            model_name='masterprofile',
            name='work_start',
        ),
        migrations.AddField(
            model_name='appointment',
            name='discount_source',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='appointment',
            name='final_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='personal_discount_percent',
            field=models.PositiveSmallIntegerField(default=0, help_text="personal client's discount, % (0–100)"),
        ),
    ]
