# Generated by Django 5.2.4 on 2025-09-03 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_appointmentitem_discount_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentitem',
            name='discount_source',
            field=models.CharField(blank=True, default='', editable=False, max_length=30),
        ),
    ]
