# Generated by Django 5.2.6 on 2025-10-08 08:35

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_drop_legacy_coumns"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Product category",
                "verbose_name_plural": "Product categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                (
                    "sku",
                    models.CharField(blank=True, max_length=64, null=True, unique=True),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Default retail price (CAD).",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                ("quantity_in_stock", models.PositiveIntegerField(default=0)),
                (
                    "low_stock_threshold",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Set >0 to flag products that need restock.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="core.productcategory",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ProductSale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sold_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Price per unit at the time of sale.",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        editable=False,
                        help_text="Computed total for reporting.",
                        max_digits=12,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        help_text="Client receiving the product (optional).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="retail_purchases",
                        to="core.userprofile",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales",
                        to="core.product",
                    ),
                ),
                (
                    "sold_by",
                    models.ForeignKey(
                        help_text="Employee who processed the sale.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="product_sales",
                        to="core.userprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-sold_at", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["is_active", "name"], name="product_active_name_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productsale",
            index=models.Index(fields=["sold_at"], name="product_sale_sold_at_idx"),
        ),
        migrations.AddIndex(
            model_name="productsale",
            index=models.Index(
                fields=["product", "sold_at"], name="product_sale_product_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productsale",
            index=models.Index(
                fields=["sold_by", "sold_at"], name="product_sale_employee_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="productsale",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)),
                name="product_sale_quantity_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="productsale",
            constraint=models.CheckConstraint(
                condition=models.Q(("unit_price__gte", Decimal("0.00"))),
                name="product_sale_unit_price_positive",
            ),
        ),
    ]
