# Generated by Django 5.2.4 on 2025-08-20 17:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_masterprofile_work_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='personal_discount_percent',
            field=models.PositiveSmallIntegerField(default=0, help_text="personal client's discount, % (0–100)", validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
