# Generated by Django 5.2.4 on 2025-08-20 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_userprofile_personal_discount_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='discount_source',
            field=models.CharField(blank=True, default='', editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='final_price',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True),
        ),
    ]
