# Generated by Django 5.2.4 on 2025-10-08 22:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_productsale_appointment"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientIntakeForm",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("slug", models.SlugField(max_length=150, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "form_class",
                    models.CharField(
                        blank=True,
                        help_text="Dotted path to a Django form class that handles rendering/validation.",
                        max_length=255,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="service",
            name="pre_appointment_forms",
            field=models.ManyToManyField(
                blank=True,
                help_text="Forms the client must complete before attending this service.",
                related_name="services",
                to="core.clientintakeform",
            ),
        ),
    ]
