# Generated by Django 5.2.4 on 2025-09-08 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_appointment_discount_source'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='notification',
            name='uniq_notification_per_kind_channel',
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'updated'), _negated=True), fields=('appointment', 'kind', 'channel'), name='uniq_notification_per_kind_channel'),
        ),
    ]
