# Generated by Django 5.2.4 on 2025-08-20 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_appointment_discount_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='health_conditions',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
