# Generated by Django 5.2.4 on 2025-10-08 23:40

import uuid
from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_clientintakeform_service_pre_appointment_forms"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientintakeform",
            name="schema",
            field=models.JSONField(blank=True, default=dict),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="clientintakeform",
            name="schema_version",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="clientintakeform",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="clientintakeform",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                default=django.utils.timezone.now,
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="ClientIntakeFormSubmission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("data", models.JSONField(blank=True, default=dict)),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                ("form_schema_snapshot", models.JSONField(blank=True, default=dict)),
                ("schema_version", models.PositiveIntegerField(default=1)),
                ("is_complete", models.BooleanField(default=True)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "appointment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=models.CASCADE,
                        related_name="intake_submissions",
                        to="core.appointment",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=models.CASCADE,
                        related_name="intake_submissions",
                        to="core.userprofile",
                    ),
                ),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=models.CASCADE,
                        related_name="submissions",
                        to="core.clientintakeform",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=models.SET_NULL,
                        related_name="intake_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-submitted_at"],
            },
        ),
    ]
