# Generated by Django 5.2.4 on 2025-08-20 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_userprofile_health_conditions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentpromocode',
            name='appointment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='promocodes', to='core.appointment'),
        ),
    ]
