# Generated by Django 5.2.4 on 2025-10-08 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_clientintakeform_schema_submission"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientintakeform",
            name="schema",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
