# Generated by Django 5.2.4 on 2025-08-21 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_appointmentpromocode_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='postal_code',
            field=models.CharField(blank=True, help_text='Alberta postal code, 6 chars (e.g. T2X1A1)', max_length=6),
        ),
    ]
