# Generated by Django 5.2.4 on 2025-10-09 04:05

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_alter_clientintakeform_schema"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Shown on the public catalog cards.",
                null=True,
                upload_to=core.models.service_image_upload_to,
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="image_alt_text",
            field=models.CharField(
                blank=True,
                help_text="Accessible text for the service image; defaults to the service name.",
                max_length=120,
            ),
        ),
    ]
