# Generated by Django 5.2.4 on 2025-08-21 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_userprofile_postal_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='source',
            field=models.CharField(choices=[('online', 'Online (self-registered)'), ('offline', 'Offline (created by admin)')], default='online', editable=False, max_length=10),
        ),
    ]
