# Generated by Django 5.2.4 on 2025-10-09 18:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_service_image_service_image_alt_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentitem',
            name='duration_override_min',
            field=models.PositiveIntegerField(blank=True, help_text='Custom duration in minutes for this appointment only', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='appointmentitem',
            name='manual_discount_percent',
            field=models.PositiveSmallIntegerField(blank=True, default=0, help_text='Additional per-appointment discount in percent', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
