# Generated by Django 5.2.4 on 2025-08-21 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_userprofile_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='address',
        ),
    ]
