# Generated by Django 5.2.4 on 2025-10-09 19:46

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_appointmentitem_duration_override_min_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterMonthlySalesTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='Use the first day of the month for tracking')),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_sales_targets', to='core.masterprofile')),
            ],
            options={
                'verbose_name': 'Master sales target',
                'verbose_name_plural': 'Master sales targets',
                'ordering': ['-month', 'master__user__user__first_name', 'master__user__user__last_name'],
                'unique_together': {('master', 'month')},
            },
        ),
    ]
