# Generated by Django 5.2.4 on 2025-08-22 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_userprofile_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('reminder_48h', 'Reminder 48h'), ('reminder_3h', 'Reminder 3h'), ('other', 'Other')], default='other', max_length=32),
        ),
        migrations.AddField(
            model_name='notification',
            name='provider',
            field=models.CharField(blank=True, default='sendgrid', max_length=32),
        ),
        migrations.AddField(
            model_name='notification',
            name='provider_message_id',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='notification',
            name='status',
            field=models.CharField(default='sent', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(fields=('appointment', 'kind', 'channel'), name='uniq_notification_per_kind_channel'),
        ),
    ]
