# Generated by Django 5.2.4 on 2025-10-11 18:02

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_mastermonthlysalestarget'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stripe_customer_id', models.CharField(db_index=True, max_length=255)),
                ('stripe_payment_method_id', models.CharField(max_length=255, unique=True)),
                ('brand', models.CharField(max_length=32)),
                ('last4', models.CharField(max_length=4)),
                ('exp_month', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('exp_year', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)])),
                ('funding', models.CharField(max_length=16)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='stripe_customer_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Stripe Customer ID for billing integrations.', max_length=255),
        ),
        migrations.AlterField(
            model_name='payment',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.appointment'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='receipt_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='stripe_charge_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='stripe_payment_method_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['stripe_payment_method_id'], name='payment_method_idx'),
        ),
        migrations.AddField(
            model_name='clientcard',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='core.userprofile'),
        ),
        migrations.AddIndex(
            model_name='clientcard',
            index=models.Index(fields=['client', 'is_default'], name='clientcard_default_idx'),
        ),
        migrations.AddConstraint(
            model_name='clientcard',
            constraint=models.UniqueConstraint(fields=('client', 'stripe_payment_method_id'), name='uniq_client_card_by_method'),
        ),
    ]
