# Generated by Django 5.2.4 on 2025-08-24 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_notification_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReminderSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Visible name, e.g. '48h' or '3 hours before'", max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('offset_amount', models.PositiveIntegerField(help_text='How many hours/days before start')),
                ('offset_unit', models.CharField(choices=[('hours', 'Hours'), ('days', 'Days')], default='hours', max_length=8)),
                ('email_subject', models.CharField(default='Appointment reminder', max_length=200)),
                ('email_template', models.CharField(default='email/appointment_reminder_generic.html', help_text='Django template path', max_length=200)),
                ('slug', models.SlugField(help_text="Used for deduplication, e.g. 'rem-48h'", max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-is_active', 'offset_unit', 'offset_amount', 'name'],
            },
        ),
    ]
