# Generated by Django 5.2.4 on 2025-08-24 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_reminderschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('reminder_days', 'Reminder Days'), ('reminder_hours', 'Reminder Hours'), ('created', 'Appointment created'), ('updated', 'Appointment updated'), ('deleted', 'Appointment deleted'), ('status', 'Appointment status changed'), ('other', 'Other')], default='other', max_length=32),
        ),
        migrations.AlterField(
            model_name='reminderschedule',
            name='email_template',
            field=models.CharField(default='email/appointment_reminder.html', help_text='Django template path', max_length=200),
        ),
    ]
