# Generated by Django 5.2.4 on 2025-08-26 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_notification_kind_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('reminder_days', 'Reminder Days'), ('reminder_hours', 'Reminder Hours'), ('created', 'Appointment created'), ('updated', 'Appointment updated'), ('cancelled', 'Appointment cancelled'), ('status', 'Appointment status changed'), ('other', 'Other')], default='other', max_length=32),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='source',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], default='online', editable=False, max_length=10),
        ),
    ]
