# Generated by Django 5.2.4 on 2025-10-21 19:26

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_payment_receipt_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='receipt_pdf',
            field=models.FileField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='receipts/%Y/%m/'),
        ),
    ]
