# Generated by Django 5.2.4 on 2025-08-18 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_userprofile_notes_alter_userprofile_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
