# Generated by Django 5.2.4 on 2025-10-22 19:05

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_tax_amount_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='appointmentitem',
            new_name='core_appoin_service_023b69_idx',
            old_name='appt_item_service_start_idx',
        ),
        migrations.AlterField(
            model_name='productsale',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, help_text='Tax collected for this sale.', max_digits=12),
        ),
    ]
