# Generated by Django 5.2.4 on 2025-10-23 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_payment_receipt_pdf'),
        ('core', '0023_rename_appt_item_service_start_idx_core_appoin_service_023b69_idx_and_more'),
    ]

    operations = [
    ]
