# Generated by Django 5.2.4 on 2025-10-23 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_merge_20251022_1903'),
        ('core', '0024_servicecategory_ordering'),
    ]

    operations = [
    ]
