# Generated by Django 5.2.4 on 2025-10-23 01:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_merge_20251022_1906"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="clientintakeform",
            name="is_universal",
            field=models.BooleanField(
                default=False,
                help_text="When enabled, every client must complete this form once.",
            ),
        ),
        migrations.CreateModel(
            name="ClientIntakeAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                ("due_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="intake_assignments_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="intake_assignments",
                        to="core.userprofile",
                    ),
                ),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="intake_assignments_completed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="core.clientintakeform",
                    ),
                ),
            ],
            options={
                "verbose_name": "Client intake assignment",
                "verbose_name_plural": "Client intake assignments",
            },
        ),
        migrations.AddField(
            model_name="clientintakeformsubmission",
            name="assignment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="submissions",
                to="core.clientintakeassignment",
            ),
        ),
        migrations.AddIndex(
            model_name="clientintakeassignment",
            index=models.Index(
                fields=["client", "form"], name="core_client_client__0029d4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clientintakeassignment",
            index=models.Index(
                fields=["form", "completed_at"], name="core_client_form_id_d936b8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clientintakeassignment",
            index=models.Index(
                fields=["client", "completed_at"], name="core_client_client__a2ba77_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="clientintakeassignment",
            unique_together={("form", "client")},
        ),
    ]
