# Generated by Django 5.2.4 on 2025-10-23 01:56

from django.db import migrations, models
from django.utils.text import slugify


def populate_servicecategory_slug(apps, schema_editor):
    ServiceCategory = apps.get_model("core", "ServiceCategory")
    existing = set()
    for category in ServiceCategory.objects.all().order_by("pk"):
        if category.slug:
            existing.add(category.slug)
            continue
        base = slugify(category.name or "") or "category"
        max_length = ServiceCategory._meta.get_field("slug").max_length
        base = base[:max_length].strip("-") or "category"

        slug_candidate = base
        index = 2
        while slug_candidate in existing:
            suffix = f"-{index}"
            trimmed = base[: max_length - len(suffix)]
            slug_candidate = f"{trimmed}{suffix}".strip("-") or f"{base}-{index}"
            index += 1
        category.slug = slug_candidate
        category.save(update_fields=["slug"])
        existing.add(category.slug)


def noop_reverse(apps, schema_editor):
    # Slugs are valuable identifiers; do not wipe them on reverse migrations.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_intake_assignments"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        ALTER TABLE core_servicecategory
                        ADD COLUMN IF NOT EXISTS slug varchar(150);
                    """,
                    reverse_sql="""
                        ALTER TABLE core_servicecategory
                        DROP COLUMN IF EXISTS slug;
                    """,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="servicecategory",
                    name="slug",
                    field=models.SlugField(
                        blank=True,
                        max_length=150,
                        null=True,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.RunPython(populate_servicecategory_slug, noop_reverse),
        migrations.AlterField(
            model_name="servicecategory",
            name="slug",
            field=models.SlugField(max_length=150, unique=True),
        ),
    ]
