# Generated by Django 5.2.4 on 2025-01-09 12:00

from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_servicecategory_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicecategory",
            name="only_discounted_services",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "Automatically list every active service that currently has an in-date discount. "
                    "When enabled the category ignores manual assignments."
                ),
            ),
        ),
        migrations.AddConstraint(
            model_name="servicecategory",
            constraint=models.UniqueConstraint(
                fields=["only_discounted_services"],
                condition=Q(only_discounted_services=True),
                name="core_servicecategory_single_discount_bucket",
            ),
        ),
    ]
