# Generated by Django 5.2.4 on 2025-10-23 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_servicecategory_discount_bucket"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="billing_contact",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="billing_contact_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
