# Generated by Django 5.2.4 on 2025-10-23 16:49

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_userprofile_billing_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='card_processing_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=10),
        ),
    ]
