# Generated by Django 5.2.4 on 2025-10-24 17:52

from django.db import migrations, models


def _set_flag_for_existing(apps, schema_editor):
    Appointment = apps.get_model("core", "Appointment")
    Appointment.objects.filter(card_processing_fee__gt=0).update(apply_card_processing_fee=True)


def _unset_flag(apps, schema_editor):
    Appointment = apps.get_model("core", "Appointment")
    Appointment.objects.update(apply_card_processing_fee=False)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_appointment_card_processing_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='apply_card_processing_fee',
            field=models.BooleanField(default=False, editable=False, help_text='If true, card/Stripe processing fee is included in totals.'),
        ),
        migrations.RunPython(_set_flag_for_existing, reverse_code=_unset_flag),
    ]
