# Generated by Django 5.2.4 on 2025-10-25 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_appointment_apply_card_processing_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Internal notes, visible to staff only.'),
        ),
    ]
