# Generated by Django 5.2.4 on 2025-10-25 19:15

from datetime import timedelta

import django.db.models.deletion
from django.db import migrations, models


def _compute_end_time(item):
    service = getattr(item, "service", None)
    if not item.start_time or service is None:
        return None
    override = getattr(item, "duration_override_min", None)
    base = getattr(service, "duration_min", 0) or 0
    extra = getattr(service, "extra_time_min", 0) or 0
    minutes = int(override or (base + extra))
    return item.start_time + timedelta(minutes=minutes)


def forwards(apps, schema_editor):
    Service = apps.get_model("core", "Service")
    AppointmentItem = apps.get_model("core", "AppointmentItem")

    for service in Service.objects.exclude(room__isnull=True).select_related("room"):
        if service.room_id:
            service.allowed_rooms.add(service.room_id)

    items_to_update = []
    for item in AppointmentItem.objects.select_related("service").iterator():
        service = getattr(item, "service", None)
        updated = False

        if service and item.room_id is None:
            if getattr(service, "room_id", None):
                item.room_id = service.room_id
                updated = True

        if service and item.start_time and item.end_time is None:
            computed = _compute_end_time(item)
            if computed is not None:
                item.end_time = computed
                updated = True

        if updated:
            items_to_update.append(item)

    if items_to_update:
        AppointmentItem.objects.bulk_update(items_to_update, ["room", "end_time"])


def backwards(apps, schema_editor):
    Service = apps.get_model("core", "Service")

    for service in Service.objects.all().iterator():
        first_room = service.allowed_rooms.order_by("pk").first()
        service.room_id = getattr(first_room, "pk", None)
        service.save(update_fields=["room"])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_appointment_notes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='appointmentitem',
            new_name='appt_master_start_idx',
            old_name='core_appoin_master__42bc28_idx',
        ),
        migrations.RenameIndex(
            model_name='appointmentitem',
            new_name='appt_service_start_idx',
            old_name='core_appoin_service_023b69_idx',
        ),
        migrations.AddField(
            model_name='appointmentitem',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointmentitem',
            name='room',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appointment_items', to='core.masterroom'),
        ),
        migrations.AddField(
            model_name='service',
            name='allowed_rooms',
            field=models.ManyToManyField(blank=True, related_name='services', to='core.masterroom'),
        ),
        migrations.RunPython(forwards, backwards),
        migrations.RemoveField(
            model_name='service',
            name='room',
        ),
        migrations.AddIndex(
            model_name='appointmentitem',
            index=models.Index(fields=['room', 'start_time'], name='appt_room_start_idx'),
        ),
    ]
