# Generated by Django 5.2.4 on 2025-10-25 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_rename_admin_notes_column'),
        ('core', '0034_appointmentitem_room_exclude'),
    ]

    operations = [
    ]
