# Generated by Django 5.2.4 on 2025-10-25 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_product_import_fields'),
        ('core', '0036_fix_admin_notes_column'),
    ]

    operations = [
    ]
