# Generated by Django 5.2.4 on 2025-10-27 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_merge_20251025_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientsource',
            name='source',
            field=models.CharField(max_length=255),
        ),
    ]
