# Generated by Django 5.2.4 on 2025-10-30 00:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_appointment_item_statuses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointmentitemstatushistory',
            options={'ordering': ['-set_at', '-id'], 'verbose_name': 'Appointment item status history', 'verbose_name_plural': 'Appointment item status history'},
        ),
        migrations.AddField(
            model_name='appointmentitemstatus',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='appointmentitem',
            name='status',
            field=models.ForeignKey(blank=True, help_text='Legacy pointer to the latest status; prefer status history helpers.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='core.appointmentitemstatus'),
        ),
        migrations.AlterField(
            model_name='appointmentitemstatushistory',
            name='set_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='appointmentitemstatus',
            index=models.Index(fields=['code'], name='appt_item_status_code_idx'),
        ),
        migrations.AddIndex(
            model_name='appointmentitemstatushistory',
            index=models.Index(fields=['item', '-set_at'], name='appt_item_status_hist_idx'),
        ),
    ]
