# Generated by Django 5.2.4 on 2025-10-31 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_port_appointment_status_to_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentitem',
            name='validation_enabled',
            field=models.BooleanField(db_index=True, default=True, help_text='When off, time/room validation for this item is skipped; overlaps are allowed.'),
        ),
    ]
