# Generated by Django 5.2.4 on 2025-10-31 17:13

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class CreateModelIgnoreMissing(migrations.CreateModel):
    """CreateModel that tolerates missing table when rolling back."""

    def database_backwards(self, app_label, schema_editor, from_state, to_state):
        try:
            super().database_backwards(app_label, schema_editor, from_state, to_state)
        except Exception as exc:  # pragma: no cover - defensive guard
            message = str(exc).lower()
            if "does not exist" in message or "unknown table" in message:
                return
            raise


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_appointmentitem_validation_enabled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        CreateModelIgnoreMissing(
            name='PaymentRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Refund amount in major currency units.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('amount_minor', models.IntegerField(help_text='Refund amount in minor currency units (e.g., cents).', validators=[django.core.validators.MinValueValidator(1)])),
                ('method', models.CharField(choices=[('stripe', 'Stripe'), ('cash', 'Cash'), ('etransfer', 'E-Transfer')], max_length=20)),
                ('stripe_refund_id', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='core.appointment')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_refunds', to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='core.payment')),
            ],
            options={
                'verbose_name': 'Payment Refund',
                'verbose_name_plural': 'Payment Refunds',
                'ordering': ['-created_at'],
            },
        ),
    ]
