# Generated by Django 5.2.4 on 2025-11-13 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0048_time_off_reasons"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supportdocument",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("privacy_notice", "Privacy notice"),
                    ("email_updates", "Email updates policy"),
                    ("terms_conditions", "Terms & Conditions"),
                    ("other", "General support document"),
                ],
                help_text="Used to reference the document from code and routes.",
                max_length=32,
            ),
        ),
    ]
