# Generated by Django 5.2.6 on 2025-12-08 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0050_product_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="TranslationCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("language", models.CharField(db_index=True, max_length=8)),
                ("source_language", models.CharField(default="en", max_length=8)),
                ("source_hash", models.CharField(db_index=True, max_length=64)),
                ("source_text", models.TextField()),
                ("translated_text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["language", "source_hash"],
                        name="core_transl_languag_8d4b5d_idx",
                    )
                ],
                "unique_together": {("language", "source_hash")},
            },
        ),
    ]
