# Generated by Django 5.2.6 on 2025-12-08 21:59

import core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0051_translationcache"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteBranding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=core.models.branding_logo_upload_to,
                    ),
                ),
                (
                    "logo_alt_text",
                    models.CharField(blank=True, default="Site logo", max_length=255),
                ),
                (
                    "logo_width",
                    models.PositiveIntegerField(
                        default=44,
                        help_text="Desktop logo size in pixels (width & height).",
                        validators=[
                            django.core.validators.MinValueValidator(16),
                            django.core.validators.MaxValueValidator(512),
                        ],
                    ),
                ),
                (
                    "logo_width_mobile",
                    models.PositiveIntegerField(
                        default=42,
                        help_text="Mobile/compact logo size in pixels.",
                        validators=[
                            django.core.validators.MinValueValidator(12),
                            django.core.validators.MaxValueValidator(512),
                        ],
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Uncheck while drafting a new logo without replacing the live one.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Site branding",
                "verbose_name_plural": "Site branding",
                "ordering": ["-updated_at"],
            },
        ),
    ]
