# Generated by Django 5.2.4 on 2025-11-15 08:19

import django.core.validators
import django.db.models.deletion
import telegrambot.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TelegramBotSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Toggle all Telegram features without editing tokens.",
                    ),
                ),
                (
                    "bot_token",
                    models.CharField(
                        blank=True,
                        help_text="Bot token issued by BotFather.",
                        max_length=255,
                    ),
                ),
                (
                    "fallback_admin_chat_ids",
                    models.TextField(
                        blank=True,
                        help_text="One chat ID per line or comma separated. Used when no admin subscriptions exist.",
                    ),
                ),
                (
                    "admin_passphrase",
                    models.CharField(
                        default=telegrambot.models._default_passphrase,
                        help_text="Secret used with /subscribe <token> to mark the chat as admin.",
                        max_length=128,
                    ),
                ),
                ("send_booking_alerts", models.BooleanField(default=True)),
                ("send_payment_alerts", models.BooleanField(default=True)),
                (
                    "allow_daily_summary_command",
                    models.BooleanField(
                        default=True, help_text="Allow /today command for admin chats."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Telegram bot settings",
                "verbose_name_plural": "Telegram bot settings",
            },
        ),
        migrations.CreateModel(
            name="TelegramChatSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chat_id",
                    models.BigIntegerField(
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^-?\\d+$", "Chat ID must be a number"
                            )
                        ],
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255)),
                ("username", models.CharField(blank=True, max_length=255)),
                ("language_code", models.CharField(blank=True, max_length=12)),
                (
                    "is_admin_channel",
                    models.BooleanField(
                        default=False,
                        help_text="Receives automatic booking/payment alerts.",
                    ),
                ),
                ("receive_broadcasts", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("last_interaction_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Telegram subscription",
                "verbose_name_plural": "Telegram subscriptions",
                "ordering": ["-is_admin_channel", "-last_interaction_at"],
            },
        ),
        migrations.CreateModel(
            name="TelegramBroadcast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("message", models.TextField()),
                (
                    "target",
                    models.CharField(
                        choices=[
                            ("admins", "Admin chats only"),
                            ("all", "All active chats"),
                        ],
                        default="admins",
                        max_length=16,
                    ),
                ),
                ("is_sent", models.BooleanField(default=False)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Telegram broadcast",
                "verbose_name_plural": "Telegram broadcasts",
                "ordering": ["-created_at"],
            },
        ),
    ]
