# Generated by Django 5.2.4 on 2025-11-15 08:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telegrambot", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="telegrambotsettings",
            name="allowed_admins",
            field=models.ManyToManyField(
                blank=True,
                help_text="Staff members allowed to configure the Telegram bot after it is locked.",
                related_name="telegrambot_delegations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="telegrambotsettings",
            name="locked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="telegrambotsettings",
            name="locked_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Once assigned, only this user or the allowed list can manage the bot.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="telegrambot_ownerships",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
