# Generated by Django 5.2.6 on 2025-11-15 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0049_alter_supportdocument_document_type"),
        ("telegrambot", "0002_telegrambotsettings_allowed_admins_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegramchatsubscription",
            name="linked_profile",
            field=models.ForeignKey(
                blank=True,
                help_text="Staff profile used to attribute Telegram commands.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="telegram_chats",
                to="core.userprofile",
            ),
        ),
    ]
