# Generated by Django 5.2.4 on 2025-01-20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0049_alter_supportdocument_document_type"),
        ("telegrambot", "0003_telegramchatsubscription_linked_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegramchatsubscription",
            name="client_profile",
            field=models.ForeignKey(
                blank=True,
                help_text="Client profile linked to this chat for booking flows.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="telegram_client_chats",
                to="core.userprofile",
            ),
        ),
        migrations.CreateModel(
            name="TelegramBookingSession",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("state", models.CharField(choices=[("idle", "Idle"), ("service", "Choosing service"), ("master", "Choosing master"), ("date", "Choosing date"), ("time", "Choosing time"), ("confirm", "Confirm")], default="idle", max_length=20)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("context_log", models.JSONField(blank=True, default=list)),
                ("active_message_id", models.BigIntegerField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("subscription", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="booking_session", to="telegrambot.telegramchatsubscription")),
            ],
            options={
                "verbose_name": "Telegram booking session",
                "verbose_name_plural": "Telegram booking sessions",
            },
        ),
    ]
