# Generated by Django 5.2.4 on 2025-11-26 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telegrambot", "0006_aiconfig_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="telegrambookingsession",
            name="state",
            field=models.CharField(
                choices=[
                    ("idle", "Idle"),
                    ("client", "Choosing client"),
                    ("service", "Choosing service"),
                    ("master", "Choosing master"),
                    ("date", "Choosing date"),
                    ("time", "Choosing time"),
                    ("confirm", "Confirm"),
                ],
                default="idle",
                max_length=20,
            ),
        ),
    ]
