from datetime import timedelta
from decimal import Decimal

from django.test import TestCase
from django.urls import reverse
from django.utils import timezone

from core.models import ServiceCategory, Service, ServiceDiscount


class ServiceCategorySlugTests(TestCase):
    def test_slug_autogenerated_from_name(self):
        category = ServiceCategory.objects.create(name="Spa Treatments")
        self.assertEqual(category.slug, "spa-treatments")

    def test_slug_collision_appends_suffix(self):
        first = ServiceCategory.objects.create(name="Massage")
        second = ServiceCategory.objects.create(name="Massage")

        self.assertEqual(first.slug, "massage")
        self.assertNotEqual(second.slug, first.slug)
        self.assertTrue(second.slug.startswith("massage-"))


class DiscountServiceCategoryTests(TestCase):
    def setUp(self):
        self.discount_category = ServiceCategory.objects.create(
            name="Promotions",
            only_discounted_services=True,
        )
        self.regular_category = ServiceCategory.objects.create(name="Massage")

        self.discounted_service = Service.objects.create(
            name="Hot Stone Massage",
            category=self.regular_category,
            base_price=Decimal("100.00"),
            duration_min=60,
        )
        self.regular_service = Service.objects.create(
            name="Swedish Massage",
            category=self.regular_category,
            base_price=Decimal("120.00"),
            duration_min=60,
        )
        today = timezone.now().date()
        ServiceDiscount.objects.create(
            service=self.discounted_service,
            discount_percent=15,
            start_date=today - timedelta(days=1),
            end_date=today + timedelta(days=1),
        )

    def _categories_by_id(self, response):
        return {category.pk: category for category in response.context["categories"]}

    def test_discount_category_lists_only_discounted_services(self):
        response = self.client.get(reverse("client-dashboard"))
        categories = self._categories_by_id(response)
        discount_entry = categories[self.discount_category.pk]
        regular_entry = categories[self.regular_category.pk]

        discount_names = {svc.name for svc in discount_entry.catalog_services}
        regular_names = {svc.name for svc in regular_entry.catalog_services}

        self.assertEqual(discount_names, {"Hot Stone Massage"})
        self.assertIn("Swedish Massage", regular_names)

    def test_filtering_discount_category_hides_other_categories(self):
        response = self.client.get(
            reverse("client-dashboard"),
            data={"cat": str(self.discount_category.pk)},
        )
        categories = self._categories_by_id(response)

        self.assertIn(self.discount_category.pk, categories)
        self.assertNotIn(self.regular_category.pk, categories)
        self.assertTrue(categories[self.discount_category.pk].catalog_services)


class CatalogCategoryVisibilityTests(TestCase):
    def setUp(self):
        self.visible_category = ServiceCategory.objects.create(name="Massage")
        self.empty_category = ServiceCategory.objects.create(name="Hair Care")
        self.visible_service = Service.objects.create(
            name="Deep Tissue Massage",
            category=self.visible_category,
            base_price=Decimal("150.00"),
            duration_min=90,
        )

    def test_empty_categories_removed_from_catalog_sections(self):
        response = self.client.get(reverse("client-dashboard"))
        category_ids = {category.pk for category in response.context["categories"]}

        self.assertIn(self.visible_category.pk, category_ids)
        self.assertNotIn(self.empty_category.pk, category_ids)

    def test_filter_categories_exclude_empty_options(self):
        response = self.client.get(reverse("client-dashboard"))
        filter_ids = {category.pk for category in response.context["filter_categories"]}

        self.assertIn(self.visible_category.pk, filter_ids)
        self.assertNotIn(self.empty_category.pk, filter_ids)

    def test_category_filter_shows_only_requested_category(self):
        response = self.client.get(
            reverse("client-dashboard"),
            data={"cat": str(self.visible_category.pk)},
        )
        category_ids = {category.pk for category in response.context["categories"]}

        self.assertEqual(category_ids, {self.visible_category.pk})
