from datetime import timedelta
from decimal import Decimal

from django.test import TestCase
from django.urls import reverse
from django.utils import timezone

from core.models import ServiceCategory, Service, ServiceDiscount


class ServiceCategorySlugTests(TestCase):
    def test_slug_autogenerated_from_name(self):
        category = ServiceCategory.objects.create(name="Spa Treatments")
        self.assertEqual(category.slug, "spa-treatments")

    def test_slug_collision_appends_suffix(self):
        first = ServiceCategory.objects.create(name="Massage")
        second = ServiceCategory.objects.create(name="Massage")

        self.assertEqual(first.slug, "massage")
        self.assertNotEqual(second.slug, first.slug)
        self.assertTrue(second.slug.startswith("massage-"))


class DiscountServiceCategoryTests(TestCase):
    def setUp(self):
        self.discount_category = ServiceCategory.objects.create(
            name="Promotions",
            only_discounted_services=True,
        )
        self.regular_category = ServiceCategory.objects.create(name="Massage")

        self.discounted_service = Service.objects.create(
            name="Hot Stone Massage",
            category=self.regular_category,
            base_price=Decimal("100.00"),
            duration_min=60,
        )
        self.regular_service = Service.objects.create(
            name="Swedish Massage",
            category=self.regular_category,
            base_price=Decimal("120.00"),
            duration_min=60,
        )
        today = timezone.now().date()
        ServiceDiscount.objects.create(
            service=self.discounted_service,
            discount_percent=15,
            start_date=today - timedelta(days=1),
            end_date=today + timedelta(days=1),
        )

    def _get_categories_from_response(self, response):
        categories = response.context["categories"]
        discount_entry = next(c for c in categories if c.pk == self.discount_category.pk)
        regular_entry = next(c for c in categories if c.pk == self.regular_category.pk)
        return discount_entry, regular_entry

    def test_discount_category_lists_only_discounted_services(self):
        response = self.client.get(reverse("client-dashboard"))
        discount_entry, regular_entry = self._get_categories_from_response(response)

        discount_names = {svc.name for svc in discount_entry.catalog_services}
        regular_names = {svc.name for svc in regular_entry.catalog_services}

        self.assertEqual(discount_names, {"Hot Stone Massage"})
        self.assertIn("Swedish Massage", regular_names)

    def test_filtering_discount_category_hides_other_categories(self):
        response = self.client.get(
            reverse("client-dashboard"),
            data={"cat": str(self.discount_category.pk)},
        )
        discount_entry, regular_entry = self._get_categories_from_response(response)

        self.assertTrue(discount_entry.catalog_services)
        self.assertFalse(regular_entry.catalog_services)
