from django.test import TestCase

from core.models import ServiceCategory


class ServiceCategorySlugTests(TestCase):
    def test_slug_autogenerated_from_name(self):
        category = ServiceCategory.objects.create(name="Spa Treatments")
        self.assertEqual(category.slug, "spa-treatments")

    def test_slug_collision_appends_suffix(self):
        first = ServiceCategory.objects.create(name="Massage")
        second = ServiceCategory.objects.create(name="Massage")

        self.assertEqual(first.slug, "massage")
        self.assertNotEqual(second.slug, first.slug)
        self.assertTrue(second.slug.startswith("massage-"))
